/* tslint:disable */
/* eslint-disable */
/**
 * LaterLetters Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateLetterRequestTagListValue } from './CreateLetterRequestTagListValue';
import {
    CreateLetterRequestTagListValueFromJSON,
    CreateLetterRequestTagListValueFromJSONTyped,
    CreateLetterRequestTagListValueToJSON,
} from './CreateLetterRequestTagListValue';

/**
 * 
 * @export
 * @interface CreateLetterRequest
 */
export interface CreateLetterRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateLetterRequest
     */
    body?: string;
    /**
     * 
     * @type {{ [key: string]: CreateLetterRequestTagListValue; }}
     * @memberof CreateLetterRequest
     */
    tagList?: { [key: string]: CreateLetterRequestTagListValue; };
}

/**
 * Check if a given object implements the CreateLetterRequest interface.
 */
export function instanceOfCreateLetterRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateLetterRequestFromJSON(json: any): CreateLetterRequest {
    return CreateLetterRequestFromJSONTyped(json, false);
}

export function CreateLetterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLetterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': !exists(json, 'body') ? undefined : json['body'],
        'tagList': !exists(json, 'tag_list') ? undefined : (mapValues(json['tag_list'], CreateLetterRequestTagListValueFromJSON)),
    };
}

export function CreateLetterRequestToJSON(value?: CreateLetterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
        'tag_list': value.tagList === undefined ? undefined : (mapValues(value.tagList, CreateLetterRequestTagListValueToJSON)),
    };
}

