/* tslint:disable */
/* eslint-disable */
/**
 * LaterLetters Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUserRequest
 */
export interface LoginUserRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginUserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginUserRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the LoginUserRequest interface.
 */
export function instanceOfLoginUserRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginUserRequestFromJSON(json: any): LoginUserRequest {
    return LoginUserRequestFromJSONTyped(json, false);
}

export function LoginUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function LoginUserRequestToJSON(value?: LoginUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

